### ISSUE TITLE
[701] Could not load credentials 

### ISSUE THREAD

**Issue by RoseTremiere** [WoodySlum/QivivoBridge#1]
Many thanks for your great work, and idea to publish this API for Qivivo Thermostat as we are still waiting for the official release of this API (since more than 2 years now...)
Unfortunatly for me, it does not seem to work properly : I get the [701] Could not load credentials.
My conf is XAMPP 7.0.8 with curl enable but I guess it's more related to a change in Qivivo server side.
Does your version still working with your configuration or did you need to update your code to make it work again?
Thanks in advance.

**Comment by WoodySlum** [comment]
Hi there, thanks for support !
Qivivo added csrf token for authentication. Added this and it should work except for the method getAccountInfo() - I will try later to make this part working.

**Comment by RoseTremiere** [comment]
It's working perfectly ! 
Many thanks for your light speed fix and once more, many thanks for your great work.
It rocks !
